# Generated by Django 4.2.3 on 2023-07-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiummodel',
            name='bron_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
