# Generated by Django 4.2.3 on 2023-07-28 08:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football_app', '0002_stadiummodel_bron_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiummodel',
            name='bron_status',
        ),
        migrations.RemoveField(
            model_name='stadiummodel',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='stadiummodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stadiummodel',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='stadiummodel',
            name='user',
        ),
        migrations.CreateModel(
            name='BronModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=datetime.datetime.now)),
                ('end_at', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.IntegerField(default=0)),
                ('bron_status', models.BooleanField(default=False, null=True)),
                ('stadium', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='football_app.stadiummodel')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bron',
            },
        ),
    ]
