# Generated by Django 4.2.3 on 2023-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0004_alter_stadiummodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadiummodel',
            name='images',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
    ]
