# Generated by Django 4.2.3 on 2023-07-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('a', 'admin'), ('o', 'owner'), ('u', 'user')], max_length=1),
        ),
    ]
